wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.12.2
    cli_version: 0.16.6
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1712689916.0
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 23
      - 24
      4: 3.12.2
      5: 0.16.6
      8:
      - 4
      - 5
      13: darwin-arm64
